export const GET_BYNAME = 'GET_BYNAME'
export const GET_ALL = 'GET_ALL'
export const GET_BYREGION = 'GET_BYREGION'
export const GET_BYPOPULATION = 'GET_BYPOPULATION'
export const GET_BYTURISTICACTIVITY = 'GET_BYTURISTICACTIVITY'
export const GET_DB = 'GET_DB'
export const GET_TENCOUNTRIES = 'GET_TENCOUNTRIES'
export const GET_ALL_ACTIVITIES = 'GET_ALL_ACTIVITIES'

